sudo:
  required

services:
  - docker

language: java
jdk: oraclejdk8

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}

after_success:
  - bash <(curl -s http://codecov.io/bash)
  - docker login -u $D_USER -p $D_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export NAME=dimmetr/smlr
  - docker build -t $NAME:$COMMIT .
  - docker tag $NAME:$COMMIT $NAME:$TAG
  - docker push $NAME

notifications:
  email:
    - dimmetr@gmail.com